"""
Django settings for inventory project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from django.contrib import admin

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 构建项目内部路径，BASE_DIR指向项目根目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 安全警告：在生产环境中请保持密钥的机密性
SECRET_KEY = '$7n6(pn8a_m@d1m0o&u512o%hcaa$_eh#q4ak14+0yz51$%!d+'

# SECURITY WARNING: don't run with debug turned on in production!
# 安全警告：在生产环境中不要开启调试模式
DEBUG = True

# 允许访问的主机列表，空列表表示允许所有主机（生产环境中应该具体指定）
ALLOWED_HOSTS = []

# Application definition
# 应用定义部分

# 已安装的应用列表
INSTALLED_APPS = [
    'simpleui',  # Django SimpleUI管理界面
    'django.contrib.admin',  # Django管理后台
    'django.contrib.auth',  # Django认证系统
    'django.contrib.contenttypes',  # Django内容类型框架
    'django.contrib.sessions',  # Django会话框架
    'django.contrib.messages',  # Django消息框架
    'django.contrib.staticfiles',  # Django静态文件处理
    'init',  # 项目主应用
    'imagekit',  # 图片处理工具
]

# 中间件配置
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # 安全中间件
    'django.contrib.sessions.middleware.SessionMiddleware',  # 会话中间件
    'django.middleware.common.CommonMiddleware',  # 通用中间件
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF保护中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 认证中间件
    'django.contrib.messages.middleware.MessageMiddleware',  # 消息中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 点击劫持保护中间件
]

# 根URL配置
ROOT_URLCONF = 'inventory.urls'

# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 使用Django模板引擎
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 模板目录
        'APP_DIRS': True,  # 是否在应用目录中查找模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # 调试上下文处理器
                'django.template.context_processors.request',  # 请求上下文处理器
                'django.contrib.auth.context_processors.auth',  # 认证上下文处理器
                'django.contrib.messages.context_processors.messages',  # 消息上下文处理器
            ],
        },
    },
]

# WSGI应用配置
WSGI_APPLICATION = 'inventory.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# 数据库配置，使用MySQL数据库

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': "inventory",  # 数据库名称
        'USER': 'root',  # 数据库用户名
        'HOST': 'localhost',  # 数据库主机地址
        'PASSWORD': '123456',  # 数据库密码
        'PORT': '3306',  # 数据库端口
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
# 密码验证配置

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # 用户属性相似性验证器
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # 最小长度验证器
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # 通用密码验证器
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # 数字密码验证器
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
# 国际化配置

LANGUAGE_CODE = 'zh-hans'  # 语言代码，简体中文

TIME_ZONE = 'Asia/Shanghai'  # 时区，上海时区

USE_I18N = True  # 是否启用国际化

USE_L10N = True  # 是否启用本地化

USE_TZ = True  # 是否启用时区支持

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# 静态文件配置（CSS, JavaScript, 图片等）

STATIC_URL = '/static/'  # 静态文件URL前缀
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # 静态文件目录
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')  # 静态文件收集目录
MEDIA_URL = '/media/'  # 媒体文件URL前缀
MEDIA_ROOT = 'C:/Users/Kj/Desktop/inventory/media/images'  # 媒体文件存储目录

# simpleui的配置
# SimpleUI管理界面配置

# logo配置
SIMPLEUI_LOGO = '/static/logo1.png'

# 修改首页设置
SIMPLEUI_HOME_PAGE = '/tasks/dashboard/'  # 首页URL
SIMPLEUI_HOME_TITLE = '控制面板'  # 首页标题
SIMPLEUI_HOME_ICON = 'fa fa-home'  # 首页图标
# AUTH_USER_MODEL = 'yourapp.CustomUser'

SIMPLEUI_INDEX='/index'
import time

# SimpleUI菜单配置
SIMPLEUI_CONFIG = {
    'system_keep': False,  # 是否保留系统菜单
    'menu_display': ['物料信息','权限认证','库存管理','物料盘点', '月底结存','安全管理'],  # 菜单显示顺序
    # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
        'app': 'init',
        'name': '物料信息',
        'icon': 'fa-solid fa-truck-front',
        'url': '/admin/init/material/',
    }, 
    {
        'name': '物料盘点',
        'icon': 'fa-solid fa-truck-fast',
        'url': '/admin/init/check_sheet/',
    },
    {
        'name': '预警报告',
        'icon': 'fa-sharp fa-solid fa-triangle-exclamation',
        'url': '',
    },
    {
        'name': '安全管理',
        'icon': 'fa-solid fa-shield-halved',
        'url': '/admin/init/backup_form/',
    },
     {
        'name': '月底结存',
        'icon': "fa-brands fa-pinterest",
        'url': '/month/',
    },
    {
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': 'auth/user/'
        }]},
        {
            'name': '库存管理',
            'icon': 'fas fa-x-ray',
            'models': [{
                'name': '出库',
                'icon': "fas fa-yin-yang",
                'url': '/admin/init/out_storage/',
            },
            {
                'app': 'init',
                'name': '入库',
                'icon': 'fas fa-wind',
                'url': '/admin/init/in_storage/'
            },
                ]
        }
    ]
}
system_keep = True

import pymysql
pymysql.install_as_MySQLdb()  # 安装PyMySQL作为MySQL数据库驱动