# Generated by Django 3.2 on 2023-05-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_form',
            fields=[
                ('B_number', models.AutoField(primary_key=True, serialize=False, verbose_name='备份序号')),
                ('B_administrator', models.CharField(max_length=20, verbose_name='备份管理员')),
                ('B_date', models.DateTimeField(auto_now_add=True, verbose_name='备份时间')),
            ],
        ),
        migrations.CreateModel(
            name='Check_sheet',
            fields=[
                ('Cnumber', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='盘点序号')),
                ('In_supplier', models.CharField(max_length=20, verbose_name='供货商')),
                ('C_date', models.DateTimeField(auto_now_add=True, verbose_name='盘点日期')),
                ('Now_inventory', models.IntegerField(verbose_name='当前库存')),
                ('Actual_num', models.IntegerField(verbose_name='实际数量')),
            ],
        ),
        migrations.CreateModel(
            name='In_storage',
            fields=[
                ('In_number', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='入库编号')),
                ('Source', models.CharField(max_length=8, verbose_name='来源途径')),
                ('In_date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('In_supplier', models.CharField(max_length=20, verbose_name='供货单位')),
                ('In_inventory', models.IntegerField(verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('Mnumber', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='物料序号')),
                ('Mname', models.CharField(max_length=10, verbose_name='名称')),
                ('Max_inventory', models.IntegerField(verbose_name='最大库存')),
                ('Min_inventory', models.IntegerField(verbose_name='最小库存')),
                ('Now_inventory', models.IntegerField(verbose_name='当前库存')),
                ('Description', models.CharField(max_length=100, verbose_name='描述信息')),
                ('Picture', models.ImageField(default='/static/logo1.png', upload_to='images', verbose_name='图片')),
                ('Price', models.FloatField(verbose_name='价格')),
                ('Now_datetime', models.DateTimeField(auto_now_add=True, verbose_name='当前时间')),
                ('Supplier', models.CharField(max_length=20, verbose_name='供货单位')),
            ],
        ),
        migrations.CreateModel(
            name='Out_storage',
            fields=[
                ('Out_number', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='出库编号')),
                ('Out_way', models.CharField(max_length=8, verbose_name='去向途径')),
                ('Out_date', models.DateTimeField(auto_now_add=True, verbose_name='出库时间')),
                ('Out_supplier', models.CharField(max_length=20, verbose_name='消耗单位')),
                ('Out_inventory', models.IntegerField(verbose_name='数量')),
                ('Mnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_storage', to='init.material', verbose_name='物料序号')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='in_storage',
            name='Mnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_storage', to='init.material', verbose_name='物料序号'),
        ),
        migrations.AddField(
            model_name='check_sheet',
            name='Mnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_sheet', to='init.material', verbose_name='物料序号'),
        ),
    ]
