# Generated by Django 3.2 on 2023-05-29 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0003_alter_material_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Now_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='当前时间'),
        ),
    ]
