# Generated by Django 3.2 on 2023-05-29 16:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0004_alter_material_now_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_storage',
            name='In_inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='in_storage',
            name='In_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='入库编号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Max_inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大库存'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Min_inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最小库存'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Now_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Now_inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='当前库存'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Picture',
            field=models.ImageField(default='/static/logo1.png', null=True, upload_to='images/', verbose_name='图片'),
        ),
    ]
