# Generated by Django 3.2 on 2023-05-30 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0005_auto_20230530_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_form',
            name='B_file',
            field=models.CharField(default='无', max_length=100, verbose_name='备份文件'),
        ),
        migrations.AlterField(
            model_name='in_storage',
            name='Mnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_storage', to='init.material', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='out_storage',
            name='Out_inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='out_storage',
            name='Out_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='出库编号'),
        ),
    ]
