# Generated by Django 3.2 on 2023-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0006_auto_20230530_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='in_storage',
            name='In_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='入库编号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Mname',
            field=models.CharField(max_length=10, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Mnumber',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='物料序号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Picture',
            field=models.ImageField(default='/static/logo1.png', null=True, upload_to='C:\\Users\\Kj\\Desktop\\inventory\\media\\images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='out_storage',
            name='Out_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='出库编号'),
        ),
    ]
