# Generated by Django 3.2 on 2023-05-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0008_auto_20230531_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_sheet',
            name='in_num',
            field=models.IntegerField(default=0, null=True, verbose_name='入库数量'),
        ),
        migrations.AlterField(
            model_name='check_sheet',
            name='out_num',
            field=models.IntegerField(default=0, null=True, verbose_name='出库数量'),
        ),
        migrations.AlterField(
            model_name='out_storage',
            name='Out_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='出库编号'),
        ),
    ]
