# Generated by Django 3.2 on 2023-05-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0009_auto_20230601_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_sheet',
            name='in_num',
        ),
        migrations.RemoveField(
            model_name='check_sheet',
            name='out_num',
        ),
    ]
