# Generated by Django 3.2 on 2025-12-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0011_alter_check_sheet_cnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.AlterField(
            model_name='check_sheet',
            name='Cnumber',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='盘点序号'),
        ),
        migrations.AlterField(
            model_name='check_sheet',
            name='Now_inventory',
            field=models.IntegerField(verbose_name='初始库存'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Picture',
            field=models.ImageField(default='/static/logo1.png', null=True, upload_to='C:\\Users\\Kj\\Desktop\\inventory\\media\\images', verbose_name='图片'),
        ),
    ]
