# Generated by Django 3.2 on 2025-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0012_auto_20251210_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Picture',
            field=models.ImageField(default='/static/logo1.png', null=True, upload_to='images/', verbose_name='图片'),
        ),
    ]
